// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdimedbgtyyaongtgbhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkaW1lZGJndHl5YW9uZ3RnYmhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNTE0OTUsImV4cCI6MjA1MzgyNzQ5NX0.I85OBs7QkZjWiOUdKzhmhZJDWVpKkFxzFMBDcIgPlDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);